services:
  web:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    command: python -m src.examples.webapp.run
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  worker:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    command: celery -A src.examples.webapp.src.api.api_tasks.celery_app worker --loglevel=info
    volumes:
      - ../:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6380:6379"